In [2]:
import numpy as np # 数组常用库
import pandas as pd # 读入csv常用库
import matplotlib.pyplot as plt # 画图常用库

In [3]:
#加载数据
def load_data( train_row):
    train = pd.read_csv("train.csv")
    print(train.shape)
    X_train = train.values[0:train_row,1:] # 取下标为1-784的列（pixel0 - pixel783）
    y_train = train.values[0:train_row,0] # 取下标为0的列 (label)
    Pred_test = pd.read_csv("test.csv").values 
    return X_train, y_train, Pred_test
train_row=5000
#train_row = 42000 
Origin_X_train, Origin_y_train, Origin_X_test = load_data(train_row)

(42000, 785)


In [4]:
from sklearn.model_selection import train_test_split
#划分训练集与验证集
X_train,X_vali, y_train, y_vali = train_test_split(Origin_X_train,Origin_y_train,test_size = 0.2,random_state = 0)

In [5]:
import time
from knn_implementation import KNNClassifier

In [ ]:
#在小规模下确定K取值
from sklearn.metrics import accuracy_score
k_range = range(3, 8)
scores = []
for k in k_range:
    print("k = " + str(k) + " begin ")
    start = time.time()
    knn = KNNClassifier(k)
    model = knn.fit(X_train,y_train)
    y_pred=model.evalue(X_vali,y_vali)
    accuracy = accuracy_score(y_vali,y_pred)   
    scores.append(accuracy)
    end = time.time()
    print("Complete time: " + str(end-start) + " Secs.")

In [ ]:
#展示准确率随K值变化情况
print (scores)
plt.plot(k_range,scores)
plt.xlabel('Value of K')
plt.ylabel('Testing accuracy')
plt.xticks(np.arange(3, 8, 1))
plt.show()

In [27]:
#确定K=3后，对全体数据作训练和验证
k=3
knn = KNNClassifier(k)
model = knn.fit(X_train,y_train)
model.evalue(X_vali,y_vali)

accuracy:0.9707142857142858
              precision    recall  f1-score   support

           0       0.98      0.99      0.98       813
           1       0.97      0.99      0.98       961
           2       0.99      0.97      0.98       860
           3       0.97      0.97      0.97       863
           4       0.98      0.95      0.96       827
           5       0.96      0.98      0.97       756
           6       0.97      0.99      0.98       841
           7       0.96      0.98      0.97       899
           8       0.99      0.93      0.96       768
           9       0.94      0.94      0.94       812

    accuracy                           0.97      8400
   macro avg       0.97      0.97      0.97      8400
weighted avg       0.97      0.97      0.97      8400

[[803   0   1   1   1   2   3   0   1   1]
 [  0 956   2   1   0   0   0   1   1   0]
 [  8   4 832   1   1   0   2  10   2   0]
 [  1   0   2 839   0   7   0   5   4   5]
 [  1   6   0   0 788   0   4   1   0  27

In [5]:
#对测试集，就算标签，并且写到submission.csv中
knn = KNNClassifier(3)
model = knn.fit(X_train,y_train)
y_pred=model.evalue(Origin_X_test,np.ones(28000))
print(len(y_pred))

pd.DataFrame({"ImageId": list(range(1,len(y_pred)+1)),"Label": y_pred}).to_csv('submission.csv', index=False,header=True)

accuracy:0.11810714285714285
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00         0
         1.0       1.00      0.12      0.21     28000
         2.0       0.00      0.00      0.00         0
         3.0       0.00      0.00      0.00         0
         4.0       0.00      0.00      0.00         0
         5.0       0.00      0.00      0.00         0
         6.0       0.00      0.00      0.00         0
         7.0       0.00      0.00      0.00         0
         8.0       0.00      0.00      0.00         0
         9.0       0.00      0.00      0.00         0

    accuracy                           0.12     28000
   macro avg       0.10      0.01      0.02     28000
weighted avg       1.00      0.12      0.21     28000

[[   0    0    0    0    0    0    0    0    0    0]
 [2796 3307 2761 2784 2710 2534 2773 2936 2588 2811]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]


c:\Users\86152\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\86152\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\86152\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capita

In [6]:
print(y_pred)

[2, 0, 9, 9, 3, 7, 0, 3, 0, 3, 5, 7, 4, 0, 4, 3, 3, 1, 9, 0, 9, 1, 1, 5, 7, 4, 2, 7, 9, 7, 7, 5, 4, 2, 6, 2, 5, 5, 1, 6, 7, 7, 4, 9, 8, 7, 8, 2, 6, 1, 6, 8, 8, 3, 8, 2, 1, 2, 2, 0, 4, 1, 7, 0, 0, 0, 1, 9, 0, 1, 6, 5, 8, 8, 2, 8, 8, 9, 2, 3, 5, 4, 1, 0, 9, 2, 4, 3, 6, 7, 2, 0, 6, 6, 1, 4, 3, 9, 7, 4, 0, 9, 2, 0, 7, 3, 0, 5, 0, 8, 0, 0, 4, 7, 1, 7, 1, 1, 3, 3, 3, 7, 2, 8, 6, 3, 8, 7, 8, 4, 3, 5, 6, 0, 0, 0, 3, 1, 3, 6, 4, 3, 4, 5, 5, 8, 7, 7, 2, 8, 4, 3, 5, 6, 5, 3, 7, 5, 7, 8, 3, 0, 4, 5, 1, 2, 7, 6, 3, 0, 2, 7, 8, 6, 1, 3, 7, 4, 1, 2, 4, 8, 5, 2, 4, 9, 2, 1, 6, 0, 6, 1, 4, 9, 6, 0, 9, 7, 6, 9, 1, 9, 0, 9, 9, 0, 8, 4, 6, 2, 0, 9, 3, 6, 7, 2, 1, 6, 3, 4, 2, 3, 1, 0, 2, 0, 4, 6, 1, 0, 0, 4, 9, 1, 7, 3, 2, 2, 8, 6, 8, 6, 2, 8, 5, 5, 9, 8, 3, 5, 9, 7, 1, 3, 8, 4, 5, 1, 4, 5, 6, 3, 3, 5, 7, 0, 6, 8, 3, 1, 6, 0, 6, 3, 9, 5, 1, 5, 8, 4, 0, 9, 2, 0, 5, 3, 7, 1, 9, 9, 5, 7, 7, 9, 9, 6, 3, 0, 3, 3, 6, 9, 8, 2, 6, 2, 7, 1, 4, 5, 8, 5, 9, 0, 0, 3, 8, 4, 1, 8, 4, 1, 1, 9, 8, 4, 5, 1, 5, 3, 6, 3, 1, 